# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    qq.runner.abstract:
        abstract: true
        autowire: false
        autoconfigure: false
        public: true
        shared: false

    qq.runner.shell:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\ShellRunner
        tags:
            - { name: qq.runner, type: shell }

    qq.runner.command:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\CommandRunner
        calls:
            - { method: setApplication, arguments: ['@qq.app'] }
        tags:
            - { name: qq.runner, type: qq, alias: command }

    qq.runner.array:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\ArrayRunner
        tags:
            - { name: qq.runner, type: array, alias: exec, deprecated: true }

    qq.runner.blob:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\BlobRunner
        tags:
            - { name: qq.runner, type: blob }

    qq.runner.bool:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\BoolRunner
        tags:
            - { name: qq.runner, type: bool }

    qq.runner.php:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\PHPRunner
        tags:
            - { name: qq.runner, type: php }

    qq.runner.include:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\IncludeRunner
        tags:
            - { name: qq.runner, type: inc }

    qq.runner.file:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\FileRunner
        tags:
            - { name: qq.runner, type: file }

    qq.runner.docker:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\DockerRunner
        calls:
            - [setRunnerFactory, ['@qq.factory.runners']]
        tags:
            - { name: qq.runner, type: docker }

    qq.runner.view:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\ViewRunner
        tags:
            - { name: qq.runner, type: view }

    qq.runner.null:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\NullRunner
        tags:
            - { name: qq.runner, type: "null" }

    qq.runner.pdo:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\PDORunner
        arguments: ["%qq.pdo%"]
        tags:
            - { name: qq.runner, type: "pdo" }

    qq.runner.json:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\JSONRunner
        tags:
            - { name: qq.runner, type: "json" }

    qq.runner.expression:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\ExpressionRunner
        tags:
            - { name: qq.runner, type: "expr" }

    qq.runner.curl:
        parent: qq.runner.abstract
        class: WorldFactory\QQ\Services\Runners\CurlRunner
        tags:
            - { name: qq.runner, type: "curl" }
