# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    qq.builder.stage.abstract:
        abstract: true
        autowire: false
        autoconfigure: false
        public: true
        shared: false

    qq.builder.stage.array:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\ArrayStageBuilder
        tags:
            - { name: qq.builder.stage, type: array }

    qq.builder.stage.child:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\ChildStageBuilder
        tags:
            - { name: qq.builder.stage, type: child }

    qq.builder.stage.leaf:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\LeafStageBuilder
        arguments: ["@qq.factory.runners"]
        tags:
            - { name: qq.builder.stage, type: leaf }

    qq.builder.stage.condition:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\ConditionStageBuilder
        tags:
            - { name: qq.builder.stage, type: condition }

    qq.builder.stage.set_from:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\SetFromStageBuilder
        tags:
            - { name: qq.builder.stage, type: setfrom }
