# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    qq.builder.stage.abstract:
        abstract: true
        autowire: false
        autoconfigure: false
        public: true
        shared: false

    qq.builder.stage.array:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\ArrayStageBuilder
        tags:
            - { name: qq.builder.stage, type: array }

    qq.builder.stage.child:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\RunStageBuilder
        tags:
            - { name: qq.builder.stage, type: child }

    qq.builder.stage.leaf:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\StringStageBuilder
        arguments: ["@qq.factory.runners"]
        tags:
            - { name: qq.builder.stage, type: leaf }

    qq.builder.stage.condition:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\IfThenElseStageBuilder
        tags:
            - { name: qq.builder.stage, type: condition }

    qq.builder.stage.set_from:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\SetFromStageBuilder
        tags:
            - { name: qq.builder.stage, type: setfrom }

    qq.builder.stage.and:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\AndStageBuilder
        tags:
            - { name: qq.builder.stage, type: and }

    qq.builder.stage.or:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\OrStageBuilder
        tags:
            - { name: qq.builder.stage, type: or }

    qq.builder.stage.add:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\AddStageBuilder
        tags:
            - { name: qq.builder.stage, type: add }

    qq.builder.stage.trycatch:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\TryCatchStageBuilder
        tags:
            - { name: qq.builder.stage, type: trycatch }

    qq.builder.stage.whiledo:
        parent: qq.builder.stage.abstract
        class: WorldFactory\QQ\Services\StageBuilders\WhileDoStageBuilder
        tags:
            - { name: qq.builder.stage, type: whiledo }
