# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    qq.builder.step.abstract:
        abstract: true
        autowire: false
        autoconfigure: false
        public: true
        shared: false

    qq.builder.step.array:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\ArrayStepBuilder
        tags:
            - { name: qq.builder.step, type: array }

    qq.builder.step.child:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\RunStepBuilder
        tags:
            - { name: qq.builder.step, type: child }

    qq.builder.step.leaf:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\StringStepBuilder
        tags:
            - { name: qq.builder.step, type: leaf }

    qq.builder.step.condition:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\IfThenElseStepBuilder
        tags:
            - { name: qq.builder.step, type: condition }

    qq.builder.step.set_from:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\SetFromStepBuilder
        tags:
            - { name: qq.builder.step, type: setfrom }

    qq.builder.step.and:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\AndStepBuilder
        tags:
            - { name: qq.builder.step, type: and }

    qq.builder.step.or:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\OrStepBuilder
        tags:
            - { name: qq.builder.step, type: or }

    qq.builder.step.add:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\AddStepBuilder
        tags:
            - { name: qq.builder.step, type: add }

    qq.builder.step.trycatch:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\TryCatchStepBuilder
        tags:
            - { name: qq.builder.step, type: trycatch }

    qq.builder.step.whiledo:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\WhileDoStepBuilder
        tags:
            - { name: qq.builder.step, type: whiledo }

    qq.builder.step.forindo:
        parent: qq.builder.step.abstract
        class: WorldFactory\QQ\Services\StepBuilders\ForInDoStepBuilder
        tags:
            - { name: qq.builder.step, type: forindo }
