monolog:
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        deprecation_handler:
            type: service
            id: qq.handler.deprecation
            level: deprecation