monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error