imports:
    - { resource: vendor/worldfactory/qq/src/resources/libs/docker.yml }
    - { resource: vendor/worldfactory/qq/src/resources/libs/composer.yml }
    - { resource: vendor/worldfactory/qq/src/resources/libs/symfony.yml }

commands:
    phpv:
        script: php -v
        shortDescription: Display PHP version.
